basePath: /api/v1
definitions:
  entity.HelloRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  entity.HelloResponse:
    properties:
      value:
        type: string
    type: object
  state.Error:
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: archer.plus@qq.com
    name: Archer
    url: https://archer.plus
  description: common project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://archer.plus
  title: API文档
  version: "1.0"
paths:
  /users/user:
    post:
      consumes:
      - application/json
      description: Hello
      parameters:
      - description: 用户名
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/entity.HelloRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.HelloResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/state.Error'
      summary: Hello
      tags:
      - 用户
swagger: "2.0"
